name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create JAR file
        run: ls build/libs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload JAR file to release
        uses: actions/upload-artifact@v2
        with:
          name: Invaders
          path: build/libs/Invaders.jar
