name: CI Workflow

on:
  push:

permissions:
  contents: read

jobs:
  CI-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run JUnit Tests
        run: ./gradlew test

      - name: Run PMD Analysis
        run: ./gradlew pmdMain pmdTest

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-reports
          path: build/reports/tests/

      - name: Publish PMD Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: pmd-reports
          path: build/reports/pmd/

